= miscellaneous things for graphs/diagrams
:sectnums:
:toc:

== Diagram tool(chain)s

[cols="5*"]
|===
|Name|Homepage/Wiki|WYSIWYG|License|Infos

|mermaid
a|* https://github.com/mermaid-js/mermaid
* https://mermaid.js.org/
|Yes (live preview of markup changes)
|???
a|* javascript-library available for browser and nodejs CLI
* https://mermaid-js.github.io/mermaid-live-editor/#/[Live Editor]
* pleasent style (out of the box)
* embedded in gitlab and azure devops server
* does not support rank yet: https://github.com/mermaid-js/mermaid/issues/3723

|PlantUML
|https://en.wikipedia.org/wiki/PlantUML[wiki]
|No
|???
a|* cli compiler generates png from markup
* java library/server/CLI 
* unpleasent style
* widely supported

|yEd
|https://www.yworks.com/products/yed
|Yes
|???
a|* Desktop App
* browser https://www.yworks.com/products/yed-live
* yEd is freely available and runs on all major platforms: Windows, Unix/Linux, and macOS.

|draw.io
|https://drawio-app.com/
|Yes
|???
a|* online (in browser)
* Desktop App (electron)

|Pencil
|https://pencil.evolus.vn/
|Yes
|GPL v2
a|* 

|Kroki
|https://kroki.io/
|/
|???
a|* renders MANY markup languages (graphviz, mermaid, uml, etc.)

|Microsoft Visio
|https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software
|commercial MS Visio EULA
a|* Desktop App

|===


== Examples

=== dot/graphviz

visualize gRPC Channel Finite-State Machine

https://dreampuf.github.io/GraphvizOnline/#digraph%20%22gRPC%20Channel%20States%22%20%7B%0A%20%20rankdir%3DLR%3B%0A%20%20%0A%20%20node%20%5Bshape%20%3D%20doublecircle%5D%3B%20start%20SHUTDOWN%3B%0A%20%20node%20%5Bshape%20%3D%20circle%2C%20fixedsize%3Dtrue%2C%20width%3D1.4%2C%20fontsize%3D10%5D%3B%20TRANSIENT_FAILURE%3B%0A%20%20node%20%5Bshape%20%3D%20circle%2C%20fixedsize%3Dtrue%2C%20width%3D1.4%2C%20fontsize%3D12%5D%3B%0A%20%20%0A%20%20%2F%2Flayout%3Dcirco%0A%20%20%0A%20%20start%20-%3E%20IDLE%3B%0A%20%20IDLE%20-%3E%20CONNECTING%20%5Blabel%3D%22Any%20new%5CnRPC%20activity%5Cnon%20the%5Cnchannel%22%5D%3B%0A%20%20IDLE%3Ase%20-%3E%20SHUTDOWN%3Asw%20%5Bxlabel%3D%22Shutdown%5Cntriggered%5Cnby%5Cnapplication%22%2C%20style%3Ddotted%2C%20weight%3D2%5D%3B%0A%20%20CONNECTING%20-%3E%20CONNECTING%3B%0A%20%20CONNECTING%20-%3E%20READY%3B%0A%20%20CONNECTING%20-%3E%20TRANSIENT_FAILURE%3B%0A%20%20CONNECTING%20-%3E%20IDLE%3B%0A%20%20CONNECTING%20-%3E%20SHUTDOWN%20%5Blabel%3D%22Shutdown%5Cntriggered%5Cnby%5Cnapplication%22%2C%20style%3Ddotted%5D%3B%0A%20%20%23%20make%20the%20edge%20to%20appear%20on%20the%20bottom%2C%20to%20not%20overlay%20the%20edge%20to%20transient_failure%0A%20%20%23%20https%3A%2F%2Fstackoverflow.com%2Fquestions%2F12896565%2Fgraphviz-how-do-i-make-edges-not-cross-each-other-choose-self-loop-edge-posit%0A%20%20%23%20https%3A%2F%2Fgraphviz.org%2Fdocs%2Fattrs%2Fxlabel%2F%0A%20%20READY%3As%20-%3E%20READY%3As%20%5Bxlabel%3D%22successfull%5Cncommunication%22%5D%3B%0A%20%20READY%20-%3E%20TRANSIENT_FAILURE%20%5Blabel%3D%22any%20failure%22%2C%20weight%3D0%2C%20minlen%3D3%5D%3B%0A%20%20READY%20-%3E%20IDLE%20%5Blabel%3D%22IDLE_TIMEOUT%5Cnor%20GOAWAY%22%5D%3B%0A%20%20READY%20-%3E%20SHUTDOWN%20%5Blabel%3D%22Shutdown%5Cntriggered%5Cnby%5Cnapplication%22%2C%20style%3Ddotted%5D%3B%0A%20%20TRANSIENT_FAILURE%20-%3E%20CONNECTING%20%5Blabel%3D%22Wait%20time%5Cnrequired%20to%5Cnimplement%5Cn(exponential)%5Cnbackoff%5Cnis%20over%22%2C%20weight%3D2%5D%3B%20%23%20%22weight%3D2%22%20just%20to%20make%20the%20line%20straight%0A%20%20TRANSIENT_FAILURE%20-%3E%20SHUTDOWN%20%5Blabel%3D%22Shutdown%5Cntriggered%5Cnby%5Cnapplication%22%2C%20style%3Ddotted%5D%3B%0A%0A%20%20%2F%2Fstart%20%5Bshape%3DMdiamond%5D%3B%0A%20%20%2F%2Fend%20%5Bshape%3DMsquare%5D%3B%0A%20%20%0A%20%20%7Brank%3Dsame%3B%20CONNECTING%20IDLE%7D%0A%20%20%7Brank%3Dsame%3B%20TRANSIENT_FAILURE%20READY%7D%0A%20%20%2F%2F%7Brank%3Dmax%3B%20SHUTDOWN%7D%0A%7D[Example in Editor]

.code
[%collapsible]
====

[source,dot]
----
digraph "gRPC Channel States" {
  rankdir=LR;
  
  node [shape = doublecircle]; start SHUTDOWN;
  node [shape = circle, fixedsize=true, width=1.4, fontsize=10]; TRANSIENT_FAILURE;
  node [shape = circle, fixedsize=true, width=1.4, fontsize=12];
  
  //layout=circo
  
  start -> IDLE;
  IDLE -> CONNECTING [label="Any new\nRPC activity\non the\nchannel"];
  IDLE:se -> SHUTDOWN:sw [xlabel="Shutdown\ntriggered\nby\napplication", style=dotted, weight=2];
  CONNECTING -> CONNECTING;
  CONNECTING -> READY;
  CONNECTING -> TRANSIENT_FAILURE;
  CONNECTING -> IDLE;
  CONNECTING -> SHUTDOWN [label="Shutdown\ntriggered\nby\napplication", style=dotted];
  # make the edge to appear on the bottom, to not overlay the edge to transient_failure
  # https://stackoverflow.com/questions/12896565/graphviz-how-do-i-make-edges-not-cross-each-other-choose-self-loop-edge-posit
  # https://graphviz.org/docs/attrs/xlabel/
  READY:s -> READY:s [xlabel="successfull\ncommunication"];
  READY -> TRANSIENT_FAILURE [label="any failure", weight=0, minlen=3];
  READY -> IDLE [label="IDLE_TIMEOUT\nor GOAWAY"];
  READY -> SHUTDOWN [label="Shutdown\ntriggered\nby\napplication", style=dotted];
  TRANSIENT_FAILURE -> CONNECTING [label="Wait time\nrequired to\nimplement\n(exponential)\nbackoff\nis over", weight=2]; # "weight=2" just to make the line straight
  TRANSIENT_FAILURE -> SHUTDOWN [label="Shutdown\ntriggered\nby\napplication", style=dotted];

  //start [shape=Mdiamond];
  //end [shape=Msquare];
  
  {rank=same; CONNECTING IDLE}
  {rank=same; TRANSIENT_FAILURE READY}
  //{rank=max; SHUTDOWN}
}
----
====
