# Table of Content
:toc:

= Versions

|===
|Edition|ECMAScript|Major Feature|link

| |ES.Next||
|10|2019|Array functions|
|9|2018||
|8|2017||
|7|2016|async, await|
|6|2015|classes, arrow functions, let, const, templates aka. string interpolation
| http://es6-features.org/
|5|2009|strict|
|===

https://medium.com/engineered-publicis-sapient/javascript-es6-es7-es10-where-are-we-8ac044dfd964

= Build Toolchain

```
TS/ESNext  -- Transpile --> ES5 (still with import/require) -- bundler --> ES5 with inlined imports/require
                             
             Typescript                                        rollup
               Babel                                         browserify
                                                              webpack
                                                               parcel
```

== bundler

* https://github.com/browserify/browserify
* https://github.com/rollup/rollup

* https://github.com/Rich-Harris/sorcery
* 

= Engine/Runtimes
[%hardbreaks]
|===
|Engine|Used by|Comments

|V8
a|* Google Chrome
* Microsoft Edge (chromium based)
* Node.js
a|
[%hardbreaks]
https://github.com/v8/v8
JS Debug Protocol: "inspector" and "legacy"

|JavaScriptCore (Webkit)
a|* Safari
|

|ChakraCore
a|* Microsoft Edge (Legacy)
a|
[%hardbreaks]
https://github.com/microsoft/ChakraCore
Will not be further developep by microsoft.
Debugging JS via "v8 devtools-protocol" aka. "inspector" protocol.
https://github.com/microsoft/ChakraCore-Debugger

|Hermes
a|* React Native
a|
[%hardbreaks]
https://github.com/facebook/hermes
Just a runtime, without render-engine or browser.

|SpiderMonkey/JaegerMonkey
a|* Firefox
a|[%hardbreaks]
https://en.wikipedia.org/wiki/SpiderMonkey
https://wiki.mozilla.org/JaegerMonkey
|===

= Module Types

|===
|name|description|syntax

|AMD|https://en.wikipedia.org/wiki/Asynchronous_module_definition[asynchronous module definition]
a|


|CJS|https://en.wikipedia.org/wiki/CommonJS[CommonJS]
a|

|ESM|
a|https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules[EcmaScript/JavaScript modules]
```
import { name as circleName } from "https://example.com/shapes/circle.js";
import { name as squareName, draw } from "./shapes/square.js";

--

export function foo () { ... }
```
|===
