# Provisioning Profiles

* located at `~/Library/MobileDevice/Provisioning Profiles/*.mobileprovision` 
** `ls -lh ~/Library/MobileDevice/Provisioning\ Profiles`
** https://github.com/juwens/provision_profile_viewer
** .mobileprovision file stucture
*** dump file structure: `openssl cms -in ~/Library/MobileDevice/Provisioning\ Profiles/....mobileprovision -inform DER -cmsout -print`
*** outer format: https://en.wikipedia.org/wiki/Cryptographic_Message_Syntax[CMS - Cryptographic Message Syntax], can be read via `security cms -D -i $file`
*** inner format: plist, can be read via `/usr/libexec/PlistBuddy`
** print all profiles +
```
list_xcode_provisioning_profiles() {
    while IFS= read -rd '' f; do 
        2> /dev/null /usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin \
            <<< $(security cms -D -i "$f")

    done < <(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name '*.mobileprovision' -print0)
}
```

* display signing certificates
** `TEMP_PEM_FILE=$(mktemp) && security find-certificate -c 'Apple Distribution: MyCompanyName (1234567890)' -ap > $TEMP_PEM_FILE && openssl crl2pkcs7 -nocrl -certfile $TEMP_PEM_FILE | openssl pkcs7 -print_certs -text -noout`

* +++<del>+++http://www.nomad-cli.com/+++</del>+++ (discontinued)
* Remap Home and End Keys: https://discussions.apple.com/thread/251108215
* oppisite Touchpad and Mouse-Wheel Scrolling: https://github.com/ther0n/UnnaturalScrollWheels

=== pkg

* pkg files are just better zip file and practially install-only, they don't contain an uninstall mechanism
* uninstalling a pkg is manually possible: https://superuser.com/a/525395/62366
** after removing the files of an installed pkg, macos still lists the pkg with "pkgutil --pkgs", it must be manually discarded with `pkgutil --forget PKGID` 
* many low-level things like dotnet-sdk are installed with by a pkg

```
# list intalled packages
pkgutil --pkgs

# list pkg infos
pkgutil --pkg-info com.apple.pkg.Xcode
# output:
# package-id: com.apple.pkg.Xcode
# version: 13.4.1.0.1.1652836097
# volume: /
# location: /
# install-time: 1654702682

# list pkg content
pkgutil --files com.apple.pkg.CLTools_Executables
# output:
# Library
# Library/Developer
# Library/Developer/CommandLineTools
# Library/Developer/CommandLineTools/Library
# Library/Developer/CommandLineTools/Library/Developer
# Library/Developer/CommandLineTools/Library/Developer/Acknowledgments.pdf
# Library/Developer/CommandLineTools/Library/Developer/Frameworks
# Library/Developer/CommandLineTools/Library/Developer/Frameworks/Testing.framework
# Library/Developer/CommandLineTools/Library/Developer/Frameworks/Testing.framework/Modules
# Library/Developer/CommandLineTools/Library/Developer/Frameworks/Testing.framework/Resources

```
