## Comparison

[cols=5*]
|===
|Topic
|link:https://learn.microsoft.com/en-us/dotnet/standard/events/[good old .Net Events]
|link:https://github.com/dotnet/reactive[System.Reactive / RX.Net / Reactive Extensions]
|link:https://learn.microsoft.com/en-us/dotnet/core/extensions/channels[System.Threading.Channels]
a|`IAsyncEnumerable<T>`

// ----------- row ------------------
a|publish is blocking
[%collapsible]
====
pushing a value blocks until EVERY subscriber processed the value.

essentially: 
----
// during publish:
public void OnNext<T>(T value) {
    foreach (var subscriber in this._subscribers) {
        subscriber.OnNext(value)
    }
}
----
====
|yes
|default: yes
|unbounded: no
|


// ----------- row ------------------
a|publisher holds a strong reference to the subscriber
[%collapsible]
.example
====
And therefore keeps the publisher in alive, and can cause memory leaks if not unsubscribed. +
In essence: publisher has a list of subscribers.
====
a|default: yes: publisher -> EventHandler -> internal List -> subscriber +
 +
with Weak References: no (link:https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/weak-event-patterns[Weak event patterns])
a|default: yes: publisher -> Subject -> subscription -> subscriber + 
 +
small chance of leveraging weak-references +
(link:https://stackoverflow.com/questions/7322395/creating-a-weak-subscription-to-an-iobservable[WeakSubscribe]), but Rx internally uses a lot of Subject+Subscribe for non-trivial operations.
|Probably not: durring `await channel.ReadAsync()` only the task/runtime (by `.ContinueWith(t => ...)` ) has a reference to the subscriber
|


// ----------- row ------------------
|transform events/data with Linq
|no
a|yes +
(**vast** majority of Linq operations to map/filter/group/merge/...)
|no
|yes with link:https://github.com/dotnet/reactive?tab=readme-ov-file#linq-for-iasyncenumerable-systemlinqasync[Ix (LINQ for IAsyncEnumerable)]



// ----------- row ------------------
|fan-out (multiple consumer can receive the same value)
|yes
|yes
a|no: values are load-balanced across all subscribers +
(you can implement a relatively simple fan-out wrapper though. the wrapper subscribes to the channel and hold a list of subscribers)
|


// ----------- row ------------------

|see also
|
|
a|
* link:https://github.com/Open-NET-Libraries/Open.ChannelExtensions[Open.ChannelExtensions] (brings Rx like features for Channels)
a|
* link:https://github.com/dotnet/reactive?tab=readme-ov-file#linq-for-iasyncenumerable-systemlinqasync[Ix (LINQ for IAsyncEnumerable)]



// ----------- row: example ------------------
|example
a|[%collapsible]
.expand
====
[source,csharp]
----
public class Button
{
    public event EventHandler Click;
    protected virtual void OnClick(EventArgs e)
    {
        // publish
        Click?.Invoke(this, e);
    }
}

public class SomeClass 
{
    ctor()
    {
        var myButton = new Button();
                
        // subscribe
        myButton.Click += MyButtonClickEventHandler;
        
        // unsubscribe
        myButton.Click -= MyButtonClickEventHandler;
    }
    
    private void MyButtonClickEventHandler(object? sender, EventArgs args)
    {
      ...
    }
}
----
====
a|
[%collapsible]
.expand
====
[source,csharp]
----
public class Button
{
    private Subject<Unit> _clicks = new();
    public IObservable<Unit> Clicks => _clicks;
    
    protected virtual void OnClick(EventArgs e)
    {
        // publish
        _clicks.OnNext(Unit.Value);
    }
}

public class SomeClass 
{
    ctor()
    {
        var myButton = new Button();
                
        // subscribe
        var subscription = myButton.Clicks.Subscribe(value => {
            ...
        });
        
        // unsubscribe
        subscription.Dispose();
    }
}
----
====
|
|

|===


## glossary / disambiguation

[%header]
|===
|name|description
|mediator pattern|design pattern, separate pub/sub mediator object, publisher and subscriber have no direct connection
|
|===

## see also

- https://github.com/MassTransit/MassTransit
- https://github.com/zeromq/libzmq
- System.Collections.IAsyncEnumerable<T> + link:https://github.com/dotnet/reactive?tab=readme-ov-file#linq-for-iasyncenumerable-systemlinqasync[Ix (LINQ for IAsyncEnumerable)]
- link:https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library[System.Threading.Tasks.Dataflow]
- https://github.com/ByteAether/WeakEvent
- https://github.com/LuckyPennySoftware/MediatR