
|===
| Operating System | Details


| Windows
a| * ETW (the default windows tracing; EventSource, EventTrace, https://github.com/microsoft/perfview[PerfView])
* https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe[EventPipe]
** only managed code
* NetTrace
* https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventsource-collect-and-view-traces
* .Net Runtime offers way more events, compared to the events which profiler-providers emit. Example for providers:
** Microsoft-DotNETCore-SampleProfiler
** example usage:
*** `dotnet trace collect --providers Microsoft-DotNETCore-SampleProfiler:0x0000F00000000000:4`
*** `dotnet trace collect --providers Microsoft-DotNETRuntimeMonoProfiler:0x20000000:4`
** Microsoft-DotNETRuntimeMonoProfiler:0x20000000:4

| Linux
a| * https://en.wikipedia.org/wiki/LTTng[LTTng] (the default linux tracing)
* https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe[EventPipe]

| Android
a| * https://github.com/google/perfetto[github: Perfetto]
* https://perfetto.dev/
* (https://en.wikipedia.org/wiki/Valgrind[Valgrind])
|===

== Tutorials

* https://youtu.be/qGEeZZBwVp4?si=hPSoTJ6BKB3sTeBj[PerfView: The Ultimate .NET Performance Tool]
* https://youtu.be/TqS4OEWn6hQ?si=-5fJU6kTP4_tESwI[Pavel Yosifovich — Writing a .NET Core cross platform profiler in an hour]
* https://chnasarre.medium.com/start-a-journey-into-the-net-profiling-apis-40c76e2e36cc
* https://www.datadoghq.com/blog/engineering/dotnet-continuous-profiler-part-2/

== Docs

* https://docs.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe
** Equivalent of old ETW (and LTTng)

== Apps

* https://www.speedscope.app/ (display speedscope files)
* https://github.com/microsoft/perfview (ETW)
* https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace[dotnet trace] (only EventPipe?, maybe also ETW?)

=== PerfView rewrite async methods

Regex for GroupPats

```
^([^!]+)!([\w.]+)(?:(?:<>c__DisplayClass[0-9]{2}_[0-9]\.)?(?<open><)*(?:<(\w+Async)>)(?:b__[0-9])*(?<-open>>)*(?(open)(?!))|(Async)\()
```

Test-Data

```
System.Private.CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(MyProject.Presentation.ViewModel.Flyout.FlyoutItemViewModel/<NavigateAsync>d__34`1<MyProject.App.ViewModels.UserSettings.SettingsPageViewModel>&)
MyProject.View!MyProject.View.Utils.NavigationService.NavigateTo(System.Type)
MyProject.View!MyProject.View.Utils.NavigationService.NavigateToAsync(System.Type)
MyProject.View!MyProject.View.Utils.NavigationService.<NavigateToAsync>d__24.MoveNext()
MyProject.View!MyProject.View.Utils.NavigationService.<NavigateToAsync>d__40.MoveNext()
MyProject.View!MyProject.View.Utils.NavigationService.<>c__DisplayClass40_0.<NavigateToAsync>b__1()
MyProject.View!MyProject.View.Utils.NavigationService.<>c__DisplayClass40_0.<NavigateToAsync>b__2()
MyProject.View!MyProject.View.Utils.NavigationService.<>c__DisplayClass40_0.<<NavigateToAsync>b__2>d.MoveNext()
```
